# install-services.ansible.yml
---
- hosts: loadbalancers
  become: true
  tasks:
    - name: Installing apache
      yum: name=httpd state=present
    - name: Ensure apache starts
      service: name=httpd state=started enabled=yes
  tags: install
- hosts: webservers
  become: true
  tasks:
    - name: Installing services
      yum:
        name:
          - httpd
          - php
        state: present
      tags: install
    - name: Ensure apache starts
      service: name=httpd state=started enabled=yes
